struct tg{
	string day;
	string month;
	string year;
};
typedef struct tg TG;

NODE_HOA_DON* KhoiTaoNode(HOA_DON hd);
bool KTSOHD(DS_NHAN_VIEN dsnv, string SOHDT);
int TimNhanVienLapHoaDon(DS_NHAN_VIEN dsnv, string SOHDT);
void ThemCuoi(NODE_HOA_DON* &pHead, NODE_HOA_DON* p);
void DuyetDanhSachHoaDon(DS_NHAN_VIEN dsnv,NODE_HOA_DON* HoaDonTam[],int &SLHDX);
void DuyetDanhSachHoaDonXuat(NODE_HOA_DON* HoaDonTam[],int SLHDX);
void MenuTraHang(int &Vitri);
void TaoKhungChonVatTuTraHang(NODE_HOA_DON *HoaDonTam[],int vthdht,DS_NHAN_VIEN dsnv);
void MenuChucNangTraHang(int &Vitri);
void SoSanhVaInRa(string ChuoiSearch,NODE_HOA_DON* HoaDonTam[],int SLHDX,int &dem,int vthightlight,int &vthdht);
bool NamNhuan(int year);
int tinhSoNgayTrongThang(int month, int year);
int TinhSoNgayTrongNam(int year);
bool KTNamHopLe(int year);
bool KTThoiGianLapHoaDonHopLe(int day, int month, int year);
bool KTThoiGianHopLe(int day,int month,int year);
bool KT2KhoangTGHopLe(int daybt,int monthbd,int yearbd, int daykt,int monthkt,int yearkt);
int TinhKhoangThoiGian(int day,int month,int year);
void TimKiemHoaDon(TREE_VAT_TU &t,NODE_HOA_DON* HoaDonTam[],int SLHDX,DS_NHAN_VIEN dsnv);
void XoaDuLieuChonHoaDonTraHang(int dem);
NODE_HOA_DON* InDanhSachHoaDonTK(DS_NHAN_VIEN dsnv, int vitrihighlight,int &SoLuongSoSanh,string ChuoiSearch);
void MenuInHoaDon(int &Vitri);
void TaoKhungInHoaDon();
void XoaKhungInHoaDon();
//void InHoaDon(DS_NHAN_VIEN dsnv,int TONGSOHOADON);
void InHoaDon(TREE_VAT_TU t,DS_NHAN_VIEN dsnv,int TONGSOHOADON);
void XoaMenuChucNangInHoaDon();
void MenuInCTHD(int &Vitri);
void LietKeHoaDon(TREE_VAT_TU t,DS_NHAN_VIEN dsnv);
void MenuLietKeNhanVienLapHoaDon(int &Vitri);
int InDanhSachNhanVienTK(DS_NHAN_VIEN dsnv, int vitrihighlight,int &dem,string MANVTK);
void XoaDuLieuTimNhanVienLapHoaDon(int dem);
void XoaKhungTimKiemNhanVienLapHoaDon();
void TaoKhungInHoaDonNV();
void XoaKhungInHoaDonNV(NHAN_VIEN* nv,TG tgbd,TG tgkt);
bool KTThoiGianTrongKhoangThoiGian(Date tgtest,TG tgbd,TG tgkt);
void InHoaDonNV(NHAN_VIEN* nv,TG tgbd,TG tgkt);
void MenuLietKeHoaDon(int &Vitri);
void XoaMenuLietKeHoaDon();
void ThongKeDoanhThu(DS_NHAN_VIEN dsnv);
void ThongKeDoanhThuTheoThang(DS_NHAN_VIEN dsnv, DOANHTHU ThongKe,int nam);
void XoaDuLieuThongKe();
