void TaoKhungGiaoDienChinh(int &Vitri);
void TaoKhungInVatTu(TREE_VAT_TU tam[],int slvt);
void TaoKhungNhapVatTu(int &Vitri);
void TaoKhungDanhSachVatTu();
void HuongDanSuDungVatTu1();
void XoaHuongDanSuDungVatTu1();
void HuongDanSuDungVatTu2();
void XoaHuongDanSuDungVatTu2();
void HuongDanHieuChinhVatTu1();
void XoaHuongDanHieuChinhVatTu1();
void HuongDanSuDungNhanVien1(int doronghuongdan);
void XoaHuongDanSuDungNhanVien1(int doronghuongdan);
void HuongDanSuDungNhanVien2(int doronghuongdan);
void XoaHuongDanSuDungNhanVien2(int doronghuongdan);
void HuongDanHieuChinhNhanVien1();
void XoaHuongDanHieuChinhNhanVien1();
void HuongDanSuDungChiTietHoaDon2(int doronghuongdan);
void XoaHuongDanSuDungChiTietHoaDon2(int doronghuongdan);
void HuongDanSuDungChiTietHoaDon3(int doronghuongdan);
void HuongDanSuDungTraHang1(int doronghuongdan);
void XoaHuongDanSuDungTraHang1(int doronghuongdan);
void HuongDanSuDungTraHang2(int doronghuongdan);
void XoaHuongDanSuDungTraHang2(int doronghuongdan);
void HuongDanSuDungTraHang3(int doronghuongdan);
void XoaHuongDanSuDungTraHang3(int doronghuongdan);
void HuongDanSuDungTraHang4(int doronghuongdan);
void XoaHuongDanSuDungTraHang4(int doronghuongdan);
void HuongDanSuDungInHoaDon1(int doronghuongdan);
void XoaHuongDanSuDungInHoaDon1(int doronghuongdan);
void HuongDanSuDungInHoaDon2(int doronghuongdan);
void HuongDanSuDungLietKeHoaDon1(int doronghuongdan);
void XoaHuongDanSuDungLietKeHoaDon1(int doronghuongdan);
void MenuThemVatTu(TREE_VAT_TU &t, TREE_VAT_TU tam[], int &slvt,DS_NHAN_VIEN dsnv);
void TaoKhungNhapNhanVien();
void ChucNangNhanVien();
void MenuNhapNhanVien(int &Vitri);
void ChucNangNhanVien(DS_NHAN_VIEN &dsnv);
void TaoKhungInNhanVien(DS_NHAN_VIEN dsnv);
void TaoKhungLapHoaDon();
void MenuLapHoaDon(int &Vitri);
void MenuThemVatTuHoaDon(int &Vitri);
void TaoKhungThemVatTuHoaDon(TREE_VAT_TU t,TREE_VAT_TU tam[], int &slvt,NODE_HOA_DON *&p,DS_NHAN_VIEN dsnv,int vtdsnv);
void TaoKhungChiTietHoaDon();
void TaoKhungCTHD(NODE_HOA_DON *&p,DS_NHAN_VIEN dsnv,int vtdsnv);
void XoaKhungCTHD(int slvthdht);
int KhungThemVTHD(NODE_HOA_DON *&p,int slvthdht,TREE_VAT_TU tam[], int &slvt);
void TaoKhungThemVatTuHoaDon(TREE_VAT_TU tam[], int &slvt,NODE_HOA_DON *&p);
void ChucNangLapHoaDon(TREE_VAT_TU t,TREE_VAT_TU tam[],int slvt ,DS_NHAN_VIEN dsnv,int &TONGSOHOADON);
void TaoKhungTraHang();
void TaoKhungLietKeHoaDon();
void TaoKhungLietKeHoaDon2();
void TaoKhungThongKe();
void MenuChucNangThongKe(int &Vitri);
